metadata:
  name: consumer
kind: Deployment
spec:
  template:
    metadata:
      name: consumer
      namespace: default
      labels:
        container: consumer
        project: consumer
    spec:
      containers:
      - image: chungsju/consumer:${project.version}
        imagePullPolicy: Always
        name: consumer
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        env:
        - name: PROVIDER_PORT
          value: '8000'
        - name: APP_CONFIG_PROFILE
          value: docker
        - name: CONSUMER_PORT
          value: '7000'
        - name: PROVIDER_HOST
          value: provider-svc
        - name: BW_PROFILE
          value: Docker
        ports:
        - containerPort: 7000
  replicas: 2
  selector:
    container: consumer
    provider: fabric8
    project: consumer
    group: com.tibco.bw
